services:
  postgres:
     image: postgres:16
     container_name: orion_db
     env_file:
       - .env
     ports:
       - "${DB_PORT}:5432"
     volumes:
       - ./tablas:/docker-entrypoint-initdb.d
     restart: unless-stopped
     
  flyway:
    image: flyway/flyway:9.22
    env_file:
       - .env
    command: -url=jdbc:postgresql://postgres:${DB_PORT}/${POSTGRES_DB} \
         -user=${POSTGRES_USER} \
         -password=${POSTGRES_PASSWORD} \
         -baselineOnMigrate=true migrate

    volumes:
      - ./tablas:/flyway/sql
    depends_on:
      - postgres